"""init_osint_tables

Revision ID: ae2878296ba5
Revises: 
Create Date: 2026-05-30 22:08:43.603559

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
import models
import models.osint

revision: str = 'ae2878296ba5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('targets',
    sa.Column('target_value', sa.String(length=255), nullable=False),
    sa.Column('is_monitored', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_targets_target_value'), 'targets', ['target_value'], unique=False)
    op.create_table('entities',
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.Enum('EMAIL', 'PWD_HASH', 'API_KEY', 'SUBDOMAIN', 'COMMIT', 'IP', 'LOCATION', name='entitytype'), nullable=False),
    sa.Column('raw_value', models.osint.EncryptedString(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source_url', sa.String(), nullable=False),
    sa.Column('is_ignored', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['target_id'], ['targets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('entities')
    op.drop_index(op.f('ix_targets_target_value'), table_name='targets')
    op.drop_table('targets')
    # ### end Alembic commands ###